/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transformer.proto

package triple;

/**
 * Protobuf type {@code Request}
 */
public final class Request extends
                          com.google.protobuf.GeneratedMessageV3 implements
                                                                // @@protoc_insertion_point(message_implements:Request)
                                                                RequestOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use Request.newBuilder() to construct.
    private Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private Request() {
        serializeType_ = "";
        args_ = java.util.Collections.emptyList();
        argTypes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
            getUnknownFields() {
        return this.unknownFields;
    }

    private Request(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
            throw new NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    case 10: {
                        String s = input.readStringRequireUtf8();

                        serializeType_ = s;
                        break;
                    }
                    case 18: {
                        if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                            args_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                            mutable_bitField0_ |= 0x00000002;
                        }
                        args_.add(input.readBytes());
                        break;
                    }
                    case 26: {
                        String s = input.readStringRequireUtf8();
                        if (!((mutable_bitField0_ & 0x00000004) != 0)) {
                            argTypes_ = new com.google.protobuf.LazyStringArrayList();
                            mutable_bitField0_ |= 0x00000004;
                        }
                        argTypes_.add(s);
                        break;
                    }
                    default: {
                        if (!parseUnknownField(
                            input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                e).setUnfinishedMessage(this);
        } finally {
            if (((mutable_bitField0_ & 0x00000002) != 0)) {
                args_ = java.util.Collections.unmodifiableList(args_); // C
            }
            if (((mutable_bitField0_ & 0x00000004) != 0)) {
                argTypes_ = argTypes_.getUnmodifiableView();
            }
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
        return GenericProto.internal_static_Request_descriptor;
    }

    @Override
    protected FieldAccessorTable
            internalGetFieldAccessorTable() {
        return GenericProto.internal_static_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Request.class, Builder.class);
    }

    private int             bitField0_;
    public static final int SERIALIZETYPE_FIELD_NUMBER = 1;
    private volatile Object serializeType_;

    /**
     * <code>string serializeType = 1;</code>
     */
    public String getSerializeType() {
        Object ref = serializeType_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            serializeType_ = s;
            return s;
        }
    }

    /**
     * <code>string serializeType = 1;</code>
     */
    public com.google.protobuf.ByteString
            getSerializeTypeBytes() {
        Object ref = serializeType_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                        (String) ref);
            serializeType_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int                                ARGS_FIELD_NUMBER = 2;
    private java.util.List<com.google.protobuf.ByteString> args_;

    /**
     * <code>repeated bytes args = 2;</code>
     */
    public java.util.List<com.google.protobuf.ByteString>
            getArgsList() {
        return args_;
    }

    /**
     * <code>repeated bytes args = 2;</code>
     */
    public int getArgsCount() {
        return args_.size();
    }

    /**
     * <code>repeated bytes args = 2;</code>
     */
    public com.google.protobuf.ByteString getArgs(int index) {
        return args_.get(index);
    }

    public static final int                    ARGTYPES_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList argTypes_;

    /**
     * <code>repeated string argTypes = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
            getArgTypesList() {
        return argTypes_;
    }

    /**
     * <code>repeated string argTypes = 3;</code>
     */
    public int getArgTypesCount() {
        return argTypes_.size();
    }

    /**
     * <code>repeated string argTypes = 3;</code>
     */
    public String getArgTypes(int index) {
        return argTypes_.get(index);
    }

    /**
     * <code>repeated string argTypes = 3;</code>
     */
    public com.google.protobuf.ByteString
            getArgTypesBytes(int index) {
        return argTypes_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;

    @Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1)
            return true;
        if (isInitialized == 0)
            return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
        throws java.io.IOException {
        if (!getSerializeTypeBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 1, serializeType_);
        }
        for (int i = 0; i < args_.size(); i++) {
            output.writeBytes(2, args_.get(i));
        }
        for (int i = 0; i < argTypes_.size(); i++) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 3, argTypes_.getRaw(i));
        }
        unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1)
            return size;

        size = 0;
        if (!getSerializeTypeBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, serializeType_);
        }
        {
            int dataSize = 0;
            for (int i = 0; i < args_.size(); i++) {
                dataSize += com.google.protobuf.CodedOutputStream
                    .computeBytesSizeNoTag(args_.get(i));
            }
            size += dataSize;
            size += 1 * getArgsList().size();
        }
        {
            int dataSize = 0;
            for (int i = 0; i < argTypes_.size(); i++) {
                dataSize += computeStringSizeNoTag(argTypes_.getRaw(i));
            }
            size += dataSize;
            size += 1 * getArgTypesList().size();
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @Override
    public boolean equals(final Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof Request)) {
            return super.equals(obj);
        }
        Request other = (Request) obj;

        if (!getSerializeType()
            .equals(other.getSerializeType()))
            return false;
        if (!getArgsList()
            .equals(other.getArgsList()))
            return false;
        if (!getArgTypesList()
            .equals(other.getArgTypesList()))
            return false;
        if (!unknownFields.equals(other.unknownFields))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + SERIALIZETYPE_FIELD_NUMBER;
        hash = (53 * hash) + getSerializeType().hashCode();
        if (getArgsCount() > 0) {
            hash = (37 * hash) + ARGS_FIELD_NUMBER;
            hash = (53 * hash) + getArgsList().hashCode();
        }
        if (getArgTypesCount() > 0) {
            hash = (37 * hash) + ARGTYPES_FIELD_NUMBER;
            hash = (53 * hash) + getArgTypesList().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static Request parseFrom(
                                    java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static Request parseFrom(
                                    java.nio.ByteBuffer data,
                                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static Request parseFrom(
                                    com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static Request parseFrom(
                                    com.google.protobuf.ByteString data,
                                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static Request parseFrom(
                                    byte[] data,
                                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
    }

    public static Request parseFrom(
                                    java.io.InputStream input,
                                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
    }

    public static Request parseDelimitedFrom(
                                             java.io.InputStream input,
                                             com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static Request parseFrom(
                                    com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
    }

    public static Request parseFrom(
                                    com.google.protobuf.CodedInputStream input,
                                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(Request prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
                                        BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code Request}
     */
    public static final class Builder extends
                                     com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                                                                                            // @@protoc_insertion_point(builder_implements:Request)
                                                                                            RequestOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
                getDescriptor() {
            return GenericProto.internal_static_Request_descriptor;
        }

        @Override
        protected FieldAccessorTable
                internalGetFieldAccessorTable() {
            return GenericProto.internal_static_Request_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                    Request.class, Builder.class);
        }

        // Construct using triple.Request.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                        BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
            }
        }

        @Override
        public Builder clear() {
            super.clear();
            serializeType_ = "";

            args_ = java.util.Collections.emptyList();
            bitField0_ = (bitField0_ & ~0x00000002);
            argTypes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
            bitField0_ = (bitField0_ & ~0x00000004);
            return this;
        }

        @Override
        public com.google.protobuf.Descriptors.Descriptor
                getDescriptorForType() {
            return GenericProto.internal_static_Request_descriptor;
        }

        @Override
        public Request getDefaultInstanceForType() {
            return Request.getDefaultInstance();
        }

        @Override
        public Request build() {
            Request result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @Override
        public Request buildPartial() {
            Request result = new Request(this);
            int from_bitField0_ = bitField0_;
            int to_bitField0_ = 0;
            result.serializeType_ = serializeType_;
            if (((bitField0_ & 0x00000002) != 0)) {
                args_ = java.util.Collections.unmodifiableList(args_);
                bitField0_ = (bitField0_ & ~0x00000002);
            }
            result.args_ = args_;
            if (((bitField0_ & 0x00000004) != 0)) {
                argTypes_ = argTypes_.getUnmodifiableView();
                bitField0_ = (bitField0_ & ~0x00000004);
            }
            result.argTypes_ = argTypes_;
            result.bitField0_ = to_bitField0_;
            onBuilt();
            return result;
        }

        @Override
        public Builder clone() {
            return super.clone();
        }

        @Override
        public Builder setField(
                                com.google.protobuf.Descriptors.FieldDescriptor field,
                                Object value) {
            return super.setField(field, value);
        }

        @Override
        public Builder clearField(
                                  com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        @Override
        public Builder clearOneof(
                                  com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        @Override
        public Builder setRepeatedField(
                                        com.google.protobuf.Descriptors.FieldDescriptor field,
                                        int index, Object value) {
            return super.setRepeatedField(field, index, value);
        }

        @Override
        public Builder addRepeatedField(
                                        com.google.protobuf.Descriptors.FieldDescriptor field,
                                        Object value) {
            return super.addRepeatedField(field, value);
        }

        @Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof Request) {
                return mergeFrom((Request) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(Request other) {
            if (other == Request.getDefaultInstance())
                return this;
            if (!other.getSerializeType().isEmpty()) {
                serializeType_ = other.serializeType_;
                onChanged();
            }
            if (!other.args_.isEmpty()) {
                if (args_.isEmpty()) {
                    args_ = other.args_;
                    bitField0_ = (bitField0_ & ~0x00000002);
                } else {
                    ensureArgsIsMutable();
                    args_.addAll(other.args_);
                }
                onChanged();
            }
            if (!other.argTypes_.isEmpty()) {
                if (argTypes_.isEmpty()) {
                    argTypes_ = other.argTypes_;
                    bitField0_ = (bitField0_ & ~0x00000004);
                } else {
                    ensureArgTypesIsMutable();
                    argTypes_.addAll(other.argTypes_);
                }
                onChanged();
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        @Override
        public final boolean isInitialized() {
            return true;
        }

        @Override
        public Builder mergeFrom(
                                 com.google.protobuf.CodedInputStream input,
                                 com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
            Request parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (Request) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        private int    bitField0_;

        private Object serializeType_ = "";

        /**
         * <code>string serializeType = 1;</code>
         */
        public String getSerializeType() {
            Object ref = serializeType_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                serializeType_ = s;
                return s;
            } else {
                return (String) ref;
            }
        }

        /**
         * <code>string serializeType = 1;</code>
         */
        public com.google.protobuf.ByteString
                getSerializeTypeBytes() {
            Object ref = serializeType_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
                serializeType_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string serializeType = 1;</code>
         */
        public Builder setSerializeType(
                                        String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            serializeType_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string serializeType = 1;</code>
         */
        public Builder clearSerializeType() {

            serializeType_ = getDefaultInstance().getSerializeType();
            onChanged();
            return this;
        }

        /**
         * <code>string serializeType = 1;</code>
         */
        public Builder setSerializeTypeBytes(
                                             com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            serializeType_ = value;
            onChanged();
            return this;
        }

        private java.util.List<com.google.protobuf.ByteString> args_ = java.util.Collections.emptyList();

        private void ensureArgsIsMutable() {
            if (!((bitField0_ & 0x00000002) != 0)) {
                args_ = new java.util.ArrayList<com.google.protobuf.ByteString>(args_);
                bitField0_ |= 0x00000002;
            }
        }

        /**
         * <code>repeated bytes args = 2;</code>
         */
        public java.util.List<com.google.protobuf.ByteString>
                getArgsList() {
            return ((bitField0_ & 0x00000002) != 0) ?
                java.util.Collections.unmodifiableList(args_) : args_;
        }

        /**
         * <code>repeated bytes args = 2;</code>
         */
        public int getArgsCount() {
            return args_.size();
        }

        /**
         * <code>repeated bytes args = 2;</code>
         */
        public com.google.protobuf.ByteString getArgs(int index) {
            return args_.get(index);
        }

        /**
         * <code>repeated bytes args = 2;</code>
         */
        public Builder setArgs(
                               int index, com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            ensureArgsIsMutable();
            args_.set(index, value);
            onChanged();
            return this;
        }

        /**
         * <code>repeated bytes args = 2;</code>
         */
        public Builder addArgs(com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            ensureArgsIsMutable();
            args_.add(value);
            onChanged();
            return this;
        }

        /**
         * <code>repeated bytes args = 2;</code>
         */
        public Builder addAllArgs(
                                  Iterable<? extends com.google.protobuf.ByteString> values) {
            ensureArgsIsMutable();
            com.google.protobuf.AbstractMessageLite.Builder.addAll(
                values, args_);
            onChanged();
            return this;
        }

        /**
         * <code>repeated bytes args = 2;</code>
         */
        public Builder clearArgs() {
            args_ = java.util.Collections.emptyList();
            bitField0_ = (bitField0_ & ~0x00000002);
            onChanged();
            return this;
        }

        private com.google.protobuf.LazyStringList argTypes_ = com.google.protobuf.LazyStringArrayList.EMPTY;

        private void ensureArgTypesIsMutable() {
            if (!((bitField0_ & 0x00000004) != 0)) {
                argTypes_ = new com.google.protobuf.LazyStringArrayList(argTypes_);
                bitField0_ |= 0x00000004;
            }
        }

        /**
         * <code>repeated string argTypes = 3;</code>
         */
        public com.google.protobuf.ProtocolStringList
                getArgTypesList() {
            return argTypes_.getUnmodifiableView();
        }

        /**
         * <code>repeated string argTypes = 3;</code>
         */
        public int getArgTypesCount() {
            return argTypes_.size();
        }

        /**
         * <code>repeated string argTypes = 3;</code>
         */
        public String getArgTypes(int index) {
            return argTypes_.get(index);
        }

        /**
         * <code>repeated string argTypes = 3;</code>
         */
        public com.google.protobuf.ByteString
                getArgTypesBytes(int index) {
            return argTypes_.getByteString(index);
        }

        /**
         * <code>repeated string argTypes = 3;</code>
         */
        public Builder setArgTypes(
                                   int index, String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            ensureArgTypesIsMutable();
            argTypes_.set(index, value);
            onChanged();
            return this;
        }

        /**
         * <code>repeated string argTypes = 3;</code>
         */
        public Builder addArgTypes(
                                   String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            ensureArgTypesIsMutable();
            argTypes_.add(value);
            onChanged();
            return this;
        }

        /**
         * <code>repeated string argTypes = 3;</code>
         */
        public Builder addAllArgTypes(
                                      Iterable<String> values) {
            ensureArgTypesIsMutable();
            com.google.protobuf.AbstractMessageLite.Builder.addAll(
                values, argTypes_);
            onChanged();
            return this;
        }

        /**
         * <code>repeated string argTypes = 3;</code>
         */
        public Builder clearArgTypes() {
            argTypes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
            bitField0_ = (bitField0_ & ~0x00000004);
            onChanged();
            return this;
        }

        /**
         * <code>repeated string argTypes = 3;</code>
         */
        public Builder addArgTypesBytes(
                                        com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            ensureArgTypesIsMutable();
            argTypes_.add(value);
            onChanged();
            return this;
        }

        @Override
        public final Builder setUnknownFields(
                                              final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        @Override
        public final Builder mergeUnknownFields(
                                                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }

        // @@protoc_insertion_point(builder_scope:Request)
    }

    // @@protoc_insertion_point(class_scope:Request)
    private static final Request DEFAULT_INSTANCE;
    static {
        DEFAULT_INSTANCE = new Request();
    }

    public static Request getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Request> PARSER = new com.google.protobuf.AbstractParser<Request>() {
                                                                        @Override
                                                                        public Request parsePartialFrom(
                                                                                                        com.google.protobuf.CodedInputStream input,
                                                                                                        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                            throws com.google.protobuf.InvalidProtocolBufferException {
                                                                            return new Request(input, extensionRegistry);
                                                                        }
                                                                    };

    public static com.google.protobuf.Parser<Request> parser() {
        return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Request> getParserForType() {
        return PARSER;
    }

    @Override
    public Request getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}
