// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GrpcTestService.proto

package com.alipay.sofa.rpc.model.grpc;

/**
 * Protobuf service {@code GrpcTestService}
 */
public abstract class GrpcTestService
                                     implements com.google.protobuf.Service {
    protected GrpcTestService() {
    }

    public interface Interface {
        /**
         * <code>rpc reqString(.GrpcTestService_Request_String) returns (.GrpcTestService_Response_String);</code>
         */
        public abstract void reqString(
                                       com.google.protobuf.RpcController controller,
                                       com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String request,
                                       com.google.protobuf.RpcCallback<com.alipay.sofa.rpc.model.grpc.GrpcTestService_Response_String> done);

        /**
         * <code>rpc reqStrin_clientStream(stream .GrpcTestService_Request_String) returns (.GrpcTestService_Response_String);</code>
         */
        public abstract void reqStrinClientStream(
                                                  com.google.protobuf.RpcController controller,
                                                  com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String request,
                                                  com.google.protobuf.RpcCallback<com.alipay.sofa.rpc.model.grpc.GrpcTestService_Response_String> done);

        /**
         * <code>rpc reqString_serverStream(.GrpcTestService_Request_String) returns (stream .GrpcTestService_Response_String);</code>
         */
        public abstract void reqStringServerStream(
                                                   com.google.protobuf.RpcController controller,
                                                   com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String request,
                                                   com.google.protobuf.RpcCallback<com.alipay.sofa.rpc.model.grpc.GrpcTestService_Response_String> done);

        /**
         * <code>rpc reqString_bothStream(stream .GrpcTestService_Request_String) returns (stream .GrpcTestService_Response_String);</code>
         */
        public abstract void reqStringBothStream(
                                                 com.google.protobuf.RpcController controller,
                                                 com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String request,
                                                 com.google.protobuf.RpcCallback<com.alipay.sofa.rpc.model.grpc.GrpcTestService_Response_String> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
                                                                   final Interface impl) {
        return new GrpcTestService() {
            @java.lang.Override
            public void reqString(
                                  com.google.protobuf.RpcController controller,
                                  com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String request,
                                  com.google.protobuf.RpcCallback<com.alipay.sofa.rpc.model.grpc.GrpcTestService_Response_String> done) {
                impl.reqString(controller, request, done);
            }

            @java.lang.Override
            public void reqStrinClientStream(
                                             com.google.protobuf.RpcController controller,
                                             com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String request,
                                             com.google.protobuf.RpcCallback<com.alipay.sofa.rpc.model.grpc.GrpcTestService_Response_String> done) {
                impl.reqStrinClientStream(controller, request, done);
            }

            @java.lang.Override
            public void reqStringServerStream(
                                              com.google.protobuf.RpcController controller,
                                              com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String request,
                                              com.google.protobuf.RpcCallback<com.alipay.sofa.rpc.model.grpc.GrpcTestService_Response_String> done) {
                impl.reqStringServerStream(controller, request, done);
            }

            @java.lang.Override
            public void reqStringBothStream(
                                            com.google.protobuf.RpcController controller,
                                            com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String request,
                                            com.google.protobuf.RpcCallback<com.alipay.sofa.rpc.model.grpc.GrpcTestService_Response_String> done) {
                impl.reqStringBothStream(controller, request, done);
            }

        };
    }

    public static com.google.protobuf.BlockingService
            newReflectiveBlockingService(final BlockingInterface impl) {
        return new com.google.protobuf.BlockingService() {
            public final com.google.protobuf.Descriptors.ServiceDescriptor
                    getDescriptorForType() {
                return getDescriptor();
            }

            public final com.google.protobuf.Message callBlockingMethod(
                                                                        com.google.protobuf.Descriptors.MethodDescriptor method,
                                                                        com.google.protobuf.RpcController controller,
                                                                        com.google.protobuf.Message request)
                throws com.google.protobuf.ServiceException {
                if (method.getService() != getDescriptor()) {
                    throw new java.lang.IllegalArgumentException(
                        "Service.callBlockingMethod() given method descriptor for " +
                            "wrong service type.");
                }
                switch (method.getIndex()) {
                    case 0:
                        return impl.reqString(controller,
                            (com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String) request);
                    case 1:
                        return impl.reqStrinClientStream(controller,
                            (com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String) request);
                    case 2:
                        return impl.reqStringServerStream(controller,
                            (com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String) request);
                    case 3:
                        return impl.reqStringBothStream(controller,
                            (com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String) request);
                    default:
                        throw new java.lang.AssertionError("Can't get here.");
                }
            }

            public final com.google.protobuf.Message
                    getRequestPrototype(
                                        com.google.protobuf.Descriptors.MethodDescriptor method) {
                if (method.getService() != getDescriptor()) {
                    throw new java.lang.IllegalArgumentException(
                        "Service.getRequestPrototype() given method " +
                            "descriptor for wrong service type.");
                }
                switch (method.getIndex()) {
                    case 0:
                        return com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String.getDefaultInstance();
                    case 1:
                        return com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String.getDefaultInstance();
                    case 2:
                        return com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String.getDefaultInstance();
                    case 3:
                        return com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String.getDefaultInstance();
                    default:
                        throw new java.lang.AssertionError("Can't get here.");
                }
            }

            public final com.google.protobuf.Message
                    getResponsePrototype(
                                         com.google.protobuf.Descriptors.MethodDescriptor method) {
                if (method.getService() != getDescriptor()) {
                    throw new java.lang.IllegalArgumentException(
                        "Service.getResponsePrototype() given method " +
                            "descriptor for wrong service type.");
                }
                switch (method.getIndex()) {
                    case 0:
                        return com.alipay.sofa.rpc.model.grpc.GrpcTestService_Response_String.getDefaultInstance();
                    case 1:
                        return com.alipay.sofa.rpc.model.grpc.GrpcTestService_Response_String.getDefaultInstance();
                    case 2:
                        return com.alipay.sofa.rpc.model.grpc.GrpcTestService_Response_String.getDefaultInstance();
                    case 3:
                        return com.alipay.sofa.rpc.model.grpc.GrpcTestService_Response_String.getDefaultInstance();
                    default:
                        throw new java.lang.AssertionError("Can't get here.");
                }
            }

        };
    }

    /**
     * <code>rpc reqString(.GrpcTestService_Request_String) returns (.GrpcTestService_Response_String);</code>
     */
    public abstract void reqString(
                                   com.google.protobuf.RpcController controller,
                                   com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String request,
                                   com.google.protobuf.RpcCallback<com.alipay.sofa.rpc.model.grpc.GrpcTestService_Response_String> done);

    /**
     * <code>rpc reqStrin_clientStream(stream .GrpcTestService_Request_String) returns (.GrpcTestService_Response_String);</code>
     */
    public abstract void reqStrinClientStream(
                                              com.google.protobuf.RpcController controller,
                                              com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String request,
                                              com.google.protobuf.RpcCallback<com.alipay.sofa.rpc.model.grpc.GrpcTestService_Response_String> done);

    /**
     * <code>rpc reqString_serverStream(.GrpcTestService_Request_String) returns (stream .GrpcTestService_Response_String);</code>
     */
    public abstract void reqStringServerStream(
                                               com.google.protobuf.RpcController controller,
                                               com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String request,
                                               com.google.protobuf.RpcCallback<com.alipay.sofa.rpc.model.grpc.GrpcTestService_Response_String> done);

    /**
     * <code>rpc reqString_bothStream(stream .GrpcTestService_Request_String) returns (stream .GrpcTestService_Response_String);</code>
     */
    public abstract void reqStringBothStream(
                                             com.google.protobuf.RpcController controller,
                                             com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String request,
                                             com.google.protobuf.RpcCallback<com.alipay.sofa.rpc.model.grpc.GrpcTestService_Response_String> done);

    public static final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptor() {
        return com.alipay.sofa.rpc.model.grpc.GrpcTestServiceProto.getDescriptor().getServices().get(0);
    }

    public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
        return getDescriptor();
    }

    public final void callMethod(
                                 com.google.protobuf.Descriptors.MethodDescriptor method,
                                 com.google.protobuf.RpcController controller,
                                 com.google.protobuf.Message request,
                                 com.google.protobuf.RpcCallback<
                                 com.google.protobuf.Message> done) {
        if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
                "Service.callMethod() given method descriptor for wrong " +
                    "service type.");
        }
        switch (method.getIndex()) {
            case 0:
                this.reqString(controller, (com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String) request,
                    com.google.protobuf.RpcUtil
                        .<com.alipay.sofa.rpc.model.grpc.GrpcTestService_Response_String> specializeCallback(
                        done));
                return;
            case 1:
                this.reqStrinClientStream(controller,
                    (com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String) request,
                    com.google.protobuf.RpcUtil
                        .<com.alipay.sofa.rpc.model.grpc.GrpcTestService_Response_String> specializeCallback(
                        done));
                return;
            case 2:
                this.reqStringServerStream(controller,
                    (com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String) request,
                    com.google.protobuf.RpcUtil
                        .<com.alipay.sofa.rpc.model.grpc.GrpcTestService_Response_String> specializeCallback(
                        done));
                return;
            case 3:
                this.reqStringBothStream(controller,
                    (com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String) request,
                    com.google.protobuf.RpcUtil
                        .<com.alipay.sofa.rpc.model.grpc.GrpcTestService_Response_String> specializeCallback(
                        done));
                return;
            default:
                throw new java.lang.AssertionError("Can't get here.");
        }
    }

    public final com.google.protobuf.Message
            getRequestPrototype(
                                com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
                "Service.getRequestPrototype() given method " +
                    "descriptor for wrong service type.");
        }
        switch (method.getIndex()) {
            case 0:
                return com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String.getDefaultInstance();
            case 1:
                return com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String.getDefaultInstance();
            case 2:
                return com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String.getDefaultInstance();
            case 3:
                return com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String.getDefaultInstance();
            default:
                throw new java.lang.AssertionError("Can't get here.");
        }
    }

    public final com.google.protobuf.Message
            getResponsePrototype(
                                 com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
                "Service.getResponsePrototype() given method " +
                    "descriptor for wrong service type.");
        }
        switch (method.getIndex()) {
            case 0:
                return com.alipay.sofa.rpc.model.grpc.GrpcTestService_Response_String.getDefaultInstance();
            case 1:
                return com.alipay.sofa.rpc.model.grpc.GrpcTestService_Response_String.getDefaultInstance();
            case 2:
                return com.alipay.sofa.rpc.model.grpc.GrpcTestService_Response_String.getDefaultInstance();
            case 3:
                return com.alipay.sofa.rpc.model.grpc.GrpcTestService_Response_String.getDefaultInstance();
            default:
                throw new java.lang.AssertionError("Can't get here.");
        }
    }

    public static Stub newStub(
                               com.google.protobuf.RpcChannel channel) {
        return new Stub(channel);
    }

    public static final class Stub extends com.alipay.sofa.rpc.model.grpc.GrpcTestService implements Interface {
        private Stub(com.google.protobuf.RpcChannel channel) {
            this.channel = channel;
        }

        private final com.google.protobuf.RpcChannel channel;

        public com.google.protobuf.RpcChannel getChannel() {
            return channel;
        }

        public void reqString(
                              com.google.protobuf.RpcController controller,
                              com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String request,
                              com.google.protobuf.RpcCallback<com.alipay.sofa.rpc.model.grpc.GrpcTestService_Response_String> done) {
            channel.callMethod(
                getDescriptor().getMethods().get(0),
                controller,
                request,
                com.alipay.sofa.rpc.model.grpc.GrpcTestService_Response_String.getDefaultInstance(),
                com.google.protobuf.RpcUtil.generalizeCallback(
                    done,
                    com.alipay.sofa.rpc.model.grpc.GrpcTestService_Response_String.class,
                    com.alipay.sofa.rpc.model.grpc.GrpcTestService_Response_String.getDefaultInstance()));
        }

        public void reqStrinClientStream(
                                         com.google.protobuf.RpcController controller,
                                         com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String request,
                                         com.google.protobuf.RpcCallback<com.alipay.sofa.rpc.model.grpc.GrpcTestService_Response_String> done) {
            channel.callMethod(
                getDescriptor().getMethods().get(1),
                controller,
                request,
                com.alipay.sofa.rpc.model.grpc.GrpcTestService_Response_String.getDefaultInstance(),
                com.google.protobuf.RpcUtil.generalizeCallback(
                    done,
                    com.alipay.sofa.rpc.model.grpc.GrpcTestService_Response_String.class,
                    com.alipay.sofa.rpc.model.grpc.GrpcTestService_Response_String.getDefaultInstance()));
        }

        public void reqStringServerStream(
                                          com.google.protobuf.RpcController controller,
                                          com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String request,
                                          com.google.protobuf.RpcCallback<com.alipay.sofa.rpc.model.grpc.GrpcTestService_Response_String> done) {
            channel.callMethod(
                getDescriptor().getMethods().get(2),
                controller,
                request,
                com.alipay.sofa.rpc.model.grpc.GrpcTestService_Response_String.getDefaultInstance(),
                com.google.protobuf.RpcUtil.generalizeCallback(
                    done,
                    com.alipay.sofa.rpc.model.grpc.GrpcTestService_Response_String.class,
                    com.alipay.sofa.rpc.model.grpc.GrpcTestService_Response_String.getDefaultInstance()));
        }

        public void reqStringBothStream(
                                        com.google.protobuf.RpcController controller,
                                        com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String request,
                                        com.google.protobuf.RpcCallback<com.alipay.sofa.rpc.model.grpc.GrpcTestService_Response_String> done) {
            channel.callMethod(
                getDescriptor().getMethods().get(3),
                controller,
                request,
                com.alipay.sofa.rpc.model.grpc.GrpcTestService_Response_String.getDefaultInstance(),
                com.google.protobuf.RpcUtil.generalizeCallback(
                    done,
                    com.alipay.sofa.rpc.model.grpc.GrpcTestService_Response_String.class,
                    com.alipay.sofa.rpc.model.grpc.GrpcTestService_Response_String.getDefaultInstance()));
        }
    }

    public static BlockingInterface newBlockingStub(
                                                    com.google.protobuf.BlockingRpcChannel channel) {
        return new BlockingStub(channel);
    }

    public interface BlockingInterface {
        public com.alipay.sofa.rpc.model.grpc.GrpcTestService_Response_String reqString(
                                                                                        com.google.protobuf.RpcController controller,
                                                                                        com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String request)
            throws com.google.protobuf.ServiceException;

        public com.alipay.sofa.rpc.model.grpc.GrpcTestService_Response_String reqStrinClientStream(
                                                                                                   com.google.protobuf.RpcController controller,
                                                                                                   com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String request)
            throws com.google.protobuf.ServiceException;

        public com.alipay.sofa.rpc.model.grpc.GrpcTestService_Response_String reqStringServerStream(
                                                                                                    com.google.protobuf.RpcController controller,
                                                                                                    com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String request)
            throws com.google.protobuf.ServiceException;

        public com.alipay.sofa.rpc.model.grpc.GrpcTestService_Response_String reqStringBothStream(
                                                                                                  com.google.protobuf.RpcController controller,
                                                                                                  com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String request)
            throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
        private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
            this.channel = channel;
        }

        private final com.google.protobuf.BlockingRpcChannel channel;

        public com.alipay.sofa.rpc.model.grpc.GrpcTestService_Response_String reqString(
                                                                                        com.google.protobuf.RpcController controller,
                                                                                        com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String request)
            throws com.google.protobuf.ServiceException {
            return (com.alipay.sofa.rpc.model.grpc.GrpcTestService_Response_String) channel.callBlockingMethod(
                getDescriptor().getMethods().get(0),
                controller,
                request,
                com.alipay.sofa.rpc.model.grpc.GrpcTestService_Response_String.getDefaultInstance());
        }

        public com.alipay.sofa.rpc.model.grpc.GrpcTestService_Response_String reqStrinClientStream(
                                                                                                   com.google.protobuf.RpcController controller,
                                                                                                   com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String request)
            throws com.google.protobuf.ServiceException {
            return (com.alipay.sofa.rpc.model.grpc.GrpcTestService_Response_String) channel.callBlockingMethod(
                getDescriptor().getMethods().get(1),
                controller,
                request,
                com.alipay.sofa.rpc.model.grpc.GrpcTestService_Response_String.getDefaultInstance());
        }

        public com.alipay.sofa.rpc.model.grpc.GrpcTestService_Response_String reqStringServerStream(
                                                                                                    com.google.protobuf.RpcController controller,
                                                                                                    com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String request)
            throws com.google.protobuf.ServiceException {
            return (com.alipay.sofa.rpc.model.grpc.GrpcTestService_Response_String) channel.callBlockingMethod(
                getDescriptor().getMethods().get(2),
                controller,
                request,
                com.alipay.sofa.rpc.model.grpc.GrpcTestService_Response_String.getDefaultInstance());
        }

        public com.alipay.sofa.rpc.model.grpc.GrpcTestService_Response_String reqStringBothStream(
                                                                                                  com.google.protobuf.RpcController controller,
                                                                                                  com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String request)
            throws com.google.protobuf.ServiceException {
            return (com.alipay.sofa.rpc.model.grpc.GrpcTestService_Response_String) channel.callBlockingMethod(
                getDescriptor().getMethods().get(3),
                controller,
                request,
                com.alipay.sofa.rpc.model.grpc.GrpcTestService_Response_String.getDefaultInstance());
        }

    }

    // @@protoc_insertion_point(class_scope:GrpcTestService)
}
