// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GrpcTestService.proto

package com.alipay.sofa.rpc.model.grpc;

public interface GrpcTestService_Response_StringOrBuilder extends
                                                         // @@protoc_insertion_point(interface_extends:GrpcTestService_Response_String)
                                                         com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string result = 1;</code>
     */
    java.lang.String getResult();

    /**
     * <code>string result = 1;</code>
     */
    com.google.protobuf.ByteString
            getResultBytes();
}
