// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GrpcTestService.proto

package com.alipay.sofa.rpc.model.grpc;

/**
 * Protobuf type {@code GrpcTestService_Request_String}
 */
public final class GrpcTestService_Request_String extends
                                                 com.google.protobuf.GeneratedMessageV3 implements
                                                                                       // @@protoc_insertion_point(message_implements:GrpcTestService_Request_String)
                                                                                       GrpcTestService_Request_StringOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use GrpcTestService_Request_String.newBuilder() to construct.
    private GrpcTestService_Request_String(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private GrpcTestService_Request_String() {
        name_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
            getUnknownFields() {
        return this.unknownFields;
    }

    private GrpcTestService_Request_String(
                                           com.google.protobuf.CodedInputStream input,
                                           com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                                       throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    default: {
                        if (!parseUnknownFieldProto3(
                            input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                    case 10: {
                        java.lang.String s = input.readStringRequireUtf8();

                        name_ = s;
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                e).setUnfinishedMessage(this);
        } finally {
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
        return com.alipay.sofa.rpc.model.grpc.GrpcTestServiceProto.internal_static_GrpcTestService_Request_String_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
        return com.alipay.sofa.rpc.model.grpc.GrpcTestServiceProto.internal_static_GrpcTestService_Request_String_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String.class,
                com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String.Builder.class);
    }

    public static final int           NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;

    /**
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            name_ = s;
            return s;
        }
    }

    /**
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
            getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
            name_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    private byte memoizedIsInitialized = -1;

    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1)
            return true;
        if (isInitialized == 0)
            return false;

        memoizedIsInitialized = 1;
        return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
        throws java.io.IOException {
        if (!getNameBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
        }
        unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1)
            return size;

        size = 0;
        if (!getNameBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String)) {
            return super.equals(obj);
        }
        com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String other = (com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String) obj;

        boolean result = true;
        result = result && getName()
            .equals(other.getName());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String parseFrom(
                                                                                          java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String parseFrom(
                                                                                          java.nio.ByteBuffer data,
                                                                                          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String parseFrom(
                                                                                          com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String parseFrom(
                                                                                          com.google.protobuf.ByteString data,
                                                                                          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String parseFrom(
                                                                                          byte[] data,
                                                                                          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String parseFrom(java.io.InputStream input)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
    }

    public static com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String parseFrom(
                                                                                          java.io.InputStream input,
                                                                                          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String parseDelimitedFrom(
                                                                                                   java.io.InputStream input,
                                                                                                   com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String parseFrom(
                                                                                          com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
    }

    public static com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String parseFrom(
                                                                                          com.google.protobuf.CodedInputStream input,
                                                                                          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
                                        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code GrpcTestService_Request_String}
     */
    public static final class Builder extends
                                     com.google.protobuf.GeneratedMessageV3.Builder<Builder>
                                                                                            implements
                                                                                            // @@protoc_insertion_point(builder_implements:GrpcTestService_Request_String)
                                                                                            com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_StringOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
                getDescriptor() {
            return com.alipay.sofa.rpc.model.grpc.GrpcTestServiceProto.internal_static_GrpcTestService_Request_String_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
                internalGetFieldAccessorTable() {
            return com.alipay.sofa.rpc.model.grpc.GrpcTestServiceProto.internal_static_GrpcTestService_Request_String_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                    com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String.class,
                    com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String.Builder.class);
        }

        // Construct using com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
            }
        }

        public Builder clear() {
            super.clear();
            name_ = "";

            return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
                getDescriptorForType() {
            return com.alipay.sofa.rpc.model.grpc.GrpcTestServiceProto.internal_static_GrpcTestService_Request_String_descriptor;
        }

        public com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String getDefaultInstanceForType() {
            return com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String.getDefaultInstance();
        }

        public com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String build() {
            com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        public com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String buildPartial() {
            com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String result = new com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String(
                this);
            result.name_ = name_;
            onBuilt();
            return result;
        }

        public Builder clone() {
            return (Builder) super.clone();
        }

        public Builder setField(
                                com.google.protobuf.Descriptors.FieldDescriptor field,
                                java.lang.Object value) {
            return (Builder) super.setField(field, value);
        }

        public Builder clearField(
                                  com.google.protobuf.Descriptors.FieldDescriptor field) {
            return (Builder) super.clearField(field);
        }

        public Builder clearOneof(
                                  com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return (Builder) super.clearOneof(oneof);
        }

        public Builder setRepeatedField(
                                        com.google.protobuf.Descriptors.FieldDescriptor field,
                                        int index, java.lang.Object value) {
            return (Builder) super.setRepeatedField(field, index, value);
        }

        public Builder addRepeatedField(
                                        com.google.protobuf.Descriptors.FieldDescriptor field,
                                        java.lang.Object value) {
            return (Builder) super.addRepeatedField(field, value);
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String) {
                return mergeFrom((com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String other) {
            if (other == com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String.getDefaultInstance())
                return this;
            if (!other.getName().isEmpty()) {
                name_ = other.name_;
                onChanged();
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        public final boolean isInitialized() {
            return true;
        }

        public Builder mergeFrom(
                                 com.google.protobuf.CodedInputStream input,
                                 com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
            com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String) e
                    .getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        private java.lang.Object name_ = "";

        /**
         * <code>string name = 1;</code>
         */
        public java.lang.String getName() {
            java.lang.Object ref = name_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                name_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string name = 1;</code>
         */
        public com.google.protobuf.ByteString
                getNameBytes() {
            java.lang.Object ref = name_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
                name_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string name = 1;</code>
         */
        public Builder setName(
                               java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            name_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string name = 1;</code>
         */
        public Builder clearName() {

            name_ = getDefaultInstance().getName();
            onChanged();
            return this;
        }

        /**
         * <code>string name = 1;</code>
         */
        public Builder setNameBytes(
                                    com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            name_ = value;
            onChanged();
            return this;
        }

        public final Builder setUnknownFields(
                                              final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFieldsProto3(unknownFields);
        }

        public final Builder mergeUnknownFields(
                                                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }

        // @@protoc_insertion_point(builder_scope:GrpcTestService_Request_String)
    }

    // @@protoc_insertion_point(class_scope:GrpcTestService_Request_String)
    private static final com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String DEFAULT_INSTANCE;
    static {
        DEFAULT_INSTANCE = new com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String();
    }

    public static com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GrpcTestService_Request_String> PARSER = new com.google.protobuf.AbstractParser<GrpcTestService_Request_String>() {
                                                                                               public GrpcTestService_Request_String parsePartialFrom(
                                                                                                                                                      com.google.protobuf.CodedInputStream input,
                                                                                                                                                      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                                                                                                   throws com.google.protobuf.InvalidProtocolBufferException {
                                                                                                   return new GrpcTestService_Request_String(
                                                                                                       input,
                                                                                                       extensionRegistry);
                                                                                               }
                                                                                           };

    public static com.google.protobuf.Parser<GrpcTestService_Request_String> parser() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GrpcTestService_Request_String> getParserForType() {
        return PARSER;
    }

    public com.alipay.sofa.rpc.model.grpc.GrpcTestService_Request_String getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}
